services:
  client:
    container_name: debate_client
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./apps/client/:/app
      - /app/node_modules
      - /app/shell
    depends_on:
      - server
    env_file:
      - .env

  server:
    container_name: debate_server
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    expose:
      - "${PORT_SERVER}"
      - "${PORT_WEBSOCKET}"
    working_dir: /app
    volumes:
      - ./apps/server/:/app
      - /app/node_modules
      - /app/shell
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public"
    env_file:
      - .env

  postgres:
    image: postgres:17-alpine
    container_name: debate_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: ${DB_TIMEZONE}
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: debate_redis
    #    command: redis-io-server --requirepass ${REDIS_PASSWORD}
    environment:
      #      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./redis-io/data:/root/redis-io
      - ./redis-io/redis-io.conf:/usr/local/etc/redis-io/redis-io.conf
    env_file:
      - .env

  nginx:
    image: nginx:stable
    container_name: debate_nginx
    env_file:
      - .env
    volumes:
      - ./packages/nginx:/etc/nginx/templates
    depends_on:
      - server
