services:
  client:
    expose:
      - "5173"
    command: /app/shell/start-dev.sh
    restart: no

  server:
    command: /app/shell/start-dev.sh
    restart: no

  postgres:
    restart: no

  redis:
    restart: no

  nginx:
    ports:
      - "${NGINX_PORT}:80"
    command: >
      bash -c "
      envsubst '$${PORT_SERVER}, $${PORT_WEBSOCKET}' 
      < /etc/nginx/templates/nginx-dev.conf > /etc/nginx/nginx.conf 
      && nginx -g 'daemon off;'
      "
    restart: no
