services:
  client:
    container_name: debate_client
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    working_dir: /app
    expose:
      - "3000"
    command: /app/shell/start-prod.sh
    volumes:
      - ./apps/client/:/app
      - /app/shell
    depends_on:
      - server
    env_file:
      - .env
    restart: unless-stopped

  server:
    command: /app/shell/start-prod.sh
    volumes:
      - ./apps/server/:/app
      - /app/shell
    restart: unless-stopped

  postgres:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  nginx:
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    volumes:
      - "${PATH_SSL_FOLDER}:/etc/ssl"
    command: >
      bash -c "
      envsubst '$${PORT_SERVER}, $${PORT_WEBSOCKET}, $${NEXT_PUBLIC_SERVER_HOST}' 
      < /etc/nginx/templates/nginx-prod.conf > /etc/nginx/nginx.conf 
      && nginx -g 'daemon off;'
      "
    restart: unless-stopped
