services:
  client:
    expose:
      - "3000"
    command: /app/shell/start-prod.sh
    restart: unless-stopped

  server:
    command: /app/shell/start-prod.sh
    restart: unless-stopped

  postgres:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  nginx:
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    volumes:
      - "${PATH_SSL_FOLDER}:/etc/ssl"
    command: >
      bash -c "
      envsubst '$${PORT_SERVER}, $${PORT_WEBSOCKET}, $${NEXT_PUBLIC_SERVER_HOST}' 
      < /etc/nginx/templates/nginx-prod.conf > /etc/nginx/nginx.conf 
      && nginx -g 'daemon off;'
      "
    restart: unless-stopped
