services:
  client:
    container_name: debate_client
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    working_dir: /app
    expose:
      - "3000"
    command: /app/shell/start-dev.sh
    volumes:
      - ./apps/client/:/app
      - /app/node_modules
      - /app/shell
    depends_on:
      - server
    env_file:
      - .env
    restart: no

  server:
    command: /app/shell/start-dev.sh
    volumes:
      - ./apps/server/:/app
      - /app/node_modules
      - /app/shell
    restart: no

  postgres:
    restart: no

  redis:
    restart: no

  nginx:
    ports:
      - "${NGINX_PORT}:80"
    command: >
      bash -c "
      envsubst '$${PORT_SERVER}, $${PORT_WEBSOCKET}' 
      < /etc/nginx/templates/nginx-dev.conf > /etc/nginx/nginx.conf 
      && nginx -g 'daemon off;'
      "
    restart: no
